spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

eureka.instance.hostname=eureka-server
spring.zipkin.base-url=http://zipkin:9411