spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#Configuration to point to the address-service running within the Docker network
address.service.url=http://address-service:8082/api/address/
eureka.instance.hostname=eureka-server

spring.zipkin.base-url=http://zipkin:9411